#Please change settings in here with caution.

#You can change if the entities from spawners allow drops or not.
settings:
  allow-spawner-mobs: false

drops:
  #Each item has a base chance, which is multiplied by the chance of the entityType.
  #If you want to double the chance for all entities, you can chance the base-chance to 2 instead of 1.
  items:
    scroll-of-repairing:
      enabled: true
      base-chance: 1
  #Each mob is given an individual chance. By default, passive mobs have no chance.
  #The numbers are calculated as whole percents, so a 1 equates to 1%.
  entityType:
    #Passives
    allay: 0
    axolotl: 0
    bat: 0
    cat: 0
    chicken: 0
    cod: 0
    cow: 0
    donkey: 0
    fox: 0
    frog: 0
    glow-squid: 0
    horse: 0
    mooshroom: 0
    mule: 0
    ocelot: 0
    parrot: 0
    pig: 0
    pufferfish: 0
    rabbit: 0
    salmon: 0
    sheep: 0
    skeleton-horse: 0
    snow-golem: 0
    squid: 0
    strider: 0
    tadpole: 0
    tropical-fish: 0
    turtle: 0
    villager: 0
    wandering-trader: 0
    #Neutrals
    bee: 1
    cave-spider: 1
    dolphin: 0
    enderman: 1
    goat: 1
    iron-golem: 1
    llama: 0
    panda: 0
    piglin: 1
    polar-bear: 1
    spider: 1
    trader-llama: 0
    wolf: 1
    zombified-piglin: 1
    #Hostiles
    blaze: 2
    chicken-jockey: 5
    creeper: 2
    drowned: 2
    elder-guardian: 5
    endermite: 1
    evoker: 2
    ghast: 2
    guardian: 2
    hoglin: 2
    husk: 2
    magma-cube: 1
    phantom: 2
    piglin-brute: 3
    pillager: 2
    ravager: 5
    shulker: 1
    silverfish: 1
    skeleton: 2
    skeleton-horseman: 2
    slime: 1
    spider-jockey: 2
    stray: 2
    vex: 2
    vindicator: 2
    warden: 10
    witch: 2
    wither-skeleton: 2
    zoglin: 2
    zombie: 2
    zombie-villager: 2
    #Bosses
    ender-dragon: 10
    wither: 10


